### PR TITLE
Revert B2a handling for sbp2rinex to the approach originally proposed in #69

### PR DESCRIPTION
**Pull request by dgburr**
This PR reverts sbp2rinex back to the behaviour of using CODE_L5I for CODE_BDS3_B5I and CODE_L5Q for CODE_BDS3_B5Q since using CODE_L5D/CODE_L5P results in much worse behaviour with rnx2rtkp.

I confirmed this as follows:

1. Start off with input files: STEP_DPFB_L5_VSS_TCP_OSR_prod_10Hz_Dr_AmotechL5.sbp and Orion_CRS_L5_prod_obs.sbp

2. Convert files using current master version of sbp2rinex:
`$ sbp2rinex.master Orion_CRS_L5_prod_obs.sbp -ro BASEPOS -o Orion_CRS_L5_prod_obs_master.obs -n Orion_CRS_L5_prod_obs_master.nav`
`$ sbp2rinex.master STEP_DPFB_L5_VSS_TCP_OSR_prod_10Hz_Dr_AmotechL5.sbp -o STEP_DPFB_L5_VSS_TCP_OSR_prod_10Hz_Dr_AmotechL5_master.obs`

3. Post-process with rnx2rtkp
`$ rnx2rtkp STEP_DPFB_L5_VSS_TCP_OSR_prod_10Hz_Dr_AmotechL5_master.obs Orion_CRS_L5_prod_obs_master.obs Orion_CRS_L5_prod_obs_master.nav -w -n -o output-master.txt -sys G,E,C -z -f 3 -r -2726598.3898 -4315438.3711 3811232.7316`

Results:
```
---------------------
Solution Availability
---------------------
All fixes:      35940   99.20%
RTK fixes:      35504   97.99%
No fix:         291     0.80%
SPS:            436     1.20%
SBAS:           0       0.00%
DGPS:           0       0.00%
RTK Float:      34833   96.14%
RTK Fixed:      671     1.85%
DR:             0       0.00%
```

4. Convert files using version of sbp2rinex from this PR:
`$ sbp2rinex.diff Orion_CRS_L5_prod_obs.sbp -ro BASEPOS -o Orion_CRS_L5_prod_obs_diff.obs -n Orion_CRS_L5_prod_obs_diff.nav`
`$ sbp2rinex.diff STEP_DPFB_L5_VSS_TCP_OSR_prod_10Hz_Dr_AmotechL5.sbp -o STEP_DPFB_L5_VSS_TCP_OSR_prod_10Hz_Dr_AmotechL5_diff.obs`

5. Post-process with rnx2rtkp
`$ rnx2rtkp STEP_DPFB_L5_VSS_TCP_OSR_prod_10Hz_Dr_AmotechL5_diff.obs Orion_CRS_L5_prod_obs_diff.obs Orion_CRS_L5_prod_obs_diff.nav -w -n -o output-diff.txt -sys G,E,C -z -f 3 -r -2726598.3898 -4315438.3711 3811232.7316`

Results:
```
---------------------
Solution Availability
---------------------
All fixes:      35940   99.20%
RTK fixes:      35504   97.99%
No fix:         291     0.80%
SPS:            436     1.20%
SBAS:           0       0.00%
DGPS:           0       0.00%
RTK Float:      18219   50.29%
RTK Fixed:      17285   47.71%
DR:             0       0.00%
```
The following CDF also shows the resulting difference in behaviour.

cdf

The files used for this test can also be found at https://drive.google.com/drive/folders/1V-5MoszuAF7cBJyMB_ZeA6J7cS3nvTkL for anyone who wishes to reproduce my steps above.

### CODE REVIEW

**Comment by dgburr** [comment]
Solved by #73

**Comment by tao-swift** [comment]
This one seems a bit strange. In the *_diff.obs file, B2a's observation type is used as `C5I L5I and S5I`, but the rinex version is still 3.04, which doesn't have `OBS TYPES` defined as these for BDS B2a signal. So i think the results from `_diff.obs` are only GPS&GAL attempted ambiguity fixing + possibly single-frequency B1I for float solution. As of why master has a low fixing, i am not quite sure yet. Are BDS B2a signals used in the master processing?

**Comment by dgburr** [comment]
With the *_diff.obs files, what happens is this:

1. `decode_obsdata()` determines priority of C5I/L5I signals is 0
2. B2a signals are dropped
3. Widelane AR is good with GPS L1/GPS L5/GAL E1/GAL E5a/BDS B1

With the *_master_obs files, what happens is this:

1. `decode_obsdata()` determines priority of C5D/L5D signals is 14
2. B2a signals are kept
3. Widelane AR is poor with GPS L1/GPS L5/GAL E1/GAL E5a/BDS B1/BDS B2a

The reason is because of this check which is done in `dd_wl_mat()` (and `ddidx()`):
```
        nofix=(m==1&&rtk->opt.glomodear==0)||(m==3&&rtk->opt.bdsmodear==0);
        if (nofix) {
            continue;
        }
```
If `bdsmodear` is disabled then the problem does not occur.

**Comment by tao-swift** [comment]
> With the *_diff.obs files, what happens is this:
> 
> 1. `decode_obsdata()` determines priority of C5I/L5I signals is 0
> 2. B2a signals are dropped
> 3. Widelane AR is good with GPS L1/GPS L5/GAL E1/GAL E5a/BDS B1
> 
> With the *_master_obs files, what happens is this:
> 
> 1. `decode_obsdata()` determines priority of C5D/L5D signals is 14
> 2. B2a signals are kept
> 3. Widelane AR is poor with GPS L1/GPS L5/GAL E1/GAL E5a/BDS B1/BDS B2a
> 
> The reason is because of this check which is done in `dd_wl_mat()` (and `ddidx()`):
> 
> ```
>         nofix=(m==1&&rtk->opt.glomodear==0)||(m==3&&rtk->opt.bdsmodear==0);
>         if (nofix) {
>             continue;
>         }
> ```
> 
> If `bdsmodear` is disabled then the problem does not occur.

In your comparison, both set `bdsmodear` as 1, right? That means `nofix` for BDS will be false, and the loop won't go into `continue`?

**Comment by dgburr** [comment]
My explanation above was based upon the case where `bdsmodear` is set to 1 (i.e. current state in `master`).   If `bdsmodear` is set to 0 then the `continue` executes and the performance is good.

**Comment by tao-swift** [comment]
> My explanation above was based upon the case where `bdsmodear` is set to 1 (i.e. current state in `master`). If `bdsmodear` is set to 0 then the `continue` executes and the performance is good. You can confirm this yourself using the files which I provided.

Yeah, i agree. Without BDS, the performance should be good. I am trying to figure out if there is anything i forgot to consider during the WL fixing implementation.

**Comment by dgburr** [comment]
> Yeah, i agree. Without BDS, the performance should be good. I am trying to figure out if there is anything i forgot to consider during the WL fixing implementation.

The issue which I described above does not occur when only the GPS+GAL constellations are enabled (i.e. performance is good regardless of the value of `bdsmodear`).

However when BDS is also enabled (i.e. enabled constellations are GPS+GAL+BDS) then the performance is poor when `bdsmodear` is enabled.

**Comment by tao-swift** [comment]
> > Yeah, i agree. Without BDS, the performance should be good. I am trying to figure out if there is anything i forgot to consider during the WL fixing implementation.
> 
> The issue which I described above does not occur when only the GPS+GAL constellations are enabled (i.e. performance is good regardless of the value of `bdsmodear`).
> 
> However when BDS is also enabled (i.e. enabled constellations are GPS+GAL+BDS) then the performance is poor when `bdsmodear` is enabled.

The fixing in my real-time processing in https://snav.slack.com/archives/C02TP89J7T5/p1644533651488789 is not good, but not as bad as yours. Your data is on the 6th, Jan. Was BDS fixing supported back then?

**Comment by dgburr** [comment]
According to https://snav.slack.com/archives/C330WG1PD/p1643987613784119, Orion v12 (featuring BDS integer fixing) was deployed to the Skylark production networks on 2022-02-04.  However if we need to process logs differently depending upon the date then this is going to create a support headache, .e.g:

* Customers in CONUS processing with corrections after 2022-02-04 should enable the BDS constellation and set `bdsmodear==1` (**verification needed**)
* Customers in CONUS processing with corrections before 2022-02-04 should enable the BDS constellation and set `bdsmodear==0`
* Customers in EU should not enable BDS at all (since there is no BDS support on the Skylark EU network)

**Comment by dgburr** [comment]
At a minimum this would require that we add another command-line argument to rnx2rtkp so that customers can enable/disable `bdsmodear` depending upon the date of the observations.  I will run some tests tomorrow to confirm the performance with data from CONUS after 2022-02-04 with and without `bdsmodar` enabled.  If `bdsmodear` gives better performance then I will update #73 to introduce the new command line flag.  However I think that the default values in rtk_skylark_l1l5.conf should have BDS disabled, then the App Note can explain what is needed to enable it if they are in CONUS.

**Comment by tao-swift** [comment]
> At a minimum this would require that we add another command-line argument to rnx2rtkp so that customers can enable/disable `bdsmodear` depending upon the date of the observations. I will run some tests tomorrow to confirm the performance with data from CONUS after 2022-02-04 with and without `bdsmodar` enabled. If `bdsmodear` gives better performance then I will update #73 to introduce the new command line flag. However I think that the default values in `rtk_skylark_l1l5.conf` should have BDS disabled, and then the App Note can explain how to enable it for customers in CONUS.

yeah, that sounds good to me. Clearly there are some logics that we need to go through. Thanks for digging into this.

**Comment by dgburr** [comment]
I ran some tests today using the `PGM2_VSS_OSR_prod_10Hz_AmotechL5.sbp` log from the `2022-02-15-BayLoop` drive.

Test procedure:

1. `sbp2rinex Orion_CRS_L5_prod_obs.sbp -ro BASEPOS -o skylark.obs -n skylark.nav`
2. `sbp2rinex PGM2_VSS_OSR_prod_10Hz_AmotechL5.sbp -o rover.obs`
3. `rnx2rtkp.master rover.obs skylark.obs skylark.nav -w -n -o bdsmodear-enabled.txt -sys G,E,C -z -rb 6 -f 3`
4. `rnx2rtkp.PR73 rover.obs skylark.obs skylark.nav -w -n -o bdsmodear-disabled.txt -sys G,E,C -z -rb 6 -f 3`

Results:
bdsmodear-enabled:
```
All fixes:      82720   98.84%
RTK fixes:      80714   96.44%
No fix:         971     1.16%
SPS:            2006    2.40%
SBAS:           0       0.00%
DGPS:           0       0.00%
RTK Float:      75957   90.76%
RTK Fixed:      4757    5.68%
DR:             0       0.00%
```
bdsmodear-disabled:
```
All fixes:      82720   98.84%
RTK fixes:      80714   96.44%
No fix:         971     1.16%
SPS:            2006    2.40%
SBAS:           0       0.00%
DGPS:           0       0.00%
RTK Float:      66646   79.63%
RTK Fixed:      14068   16.81%
DR:             0       0.00%
```

cdf

So it appears that disabling `bdsmodear` gives better results, even when using Skylark data from CONUS after 2022-02-04.  Therefore I propose that we proceed with the approach suggested in https://github.com/swift-nav/RTKLIB/pull/73.

**Comment by dgburr** [comment]
I have uploaded the files used for the test above to https://drive.google.com/drive/folders/1htRtnA5f733LtI3zAVzi1b-2pDrlAucJ?usp=sharing

**Comment by tao-swift** [comment]
> I ran some tests today using the `PGM2_VSS_OSR_prod_10Hz_AmotechL5.sbp` log from the `2022-02-15-BayLoop` drive.
> 
> Test procedure:
> 
> 1. `sbp2rinex Orion_CRS_L5_prod_obs.sbp -ro BASEPOS -o skylark.obs -n skylark.nav`
> 2. `sbp2rinex PGM2_VSS_OSR_prod_10Hz_AmotechL5.sbp -o rover.obs`
> 3. `rnx2rtkp.master rover.obs skylark.obs skylark.nav -w -n -o bdsmodear-enabled.txt -sys G,E,C -z -rb 6 -f 3`
> 4. `rnx2rtkp.PR73 rover.obs skylark.obs skylark.nav -w -n -o bdsmodear-disabled.txt -sys G,E,C -z -rb 6 -f 3`
> 
> Results: bdsmodear-enabled:
> 
> ```
> All fixes:      82720   98.84%
> RTK fixes:      80714   96.44%
> No fix:         971     1.16%
> SPS:            2006    2.40%
> SBAS:           0       0.00%
> DGPS:           0       0.00%
> RTK Float:      75957   90.76%
> RTK Fixed:      4757    5.68%
> DR:             0       0.00%
> ```
> 
> bdsmodear-disabled:
> 
> ```
> All fixes:      82720   98.84%
> RTK fixes:      80714   96.44%
> No fix:         971     1.16%
> SPS:            2006    2.40%
> SBAS:           0       0.00%
> DGPS:           0       0.00%
> RTK Float:      66646   79.63%
> RTK Fixed:      14068   16.81%
> DR:             0       0.00%
> ```
> 
> cdf
> 
> So it appears that disabling `bdsmodear` gives better results, even when using Skylark data from CONUS after 2022-02-04. Therefore I propose that we proceed with the approach suggested in #73.

Will you be able to generate the plots together with the `navsys` setting as only GPS&GAL? So no BDS system enabled. The fixing rate seems to low in both enabling `bdsmodear` and disabling `bdsmodear`.

**Comment by dgburr** [comment]
Performance is worse when only using GPS+GAL (as expected)

cdf2

**Comment by tao-swift** [comment]
> Performance is worse when only using GPS+GAL (as expected)
> 
> cdf2

It looks like within 10cm position error, RTKLIB beats starling...

**Comment by dgburr** [comment]
That is correct - Starling also performed very poorly in real-time with the same local and remote observations

**Comment by dgburr** [comment]
Are you now happy to merge #73 so that we can proceed with releasing wide lane support to the public?

**Pull request closed without merging**
