### PR TITLE
Add support for new GPS and GLO ephemeris

### PR DESCRIPTION
**Pull request by Paakkit**
Step 2. in the introduction of new SBP ephemeris messages.

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-66-gefb32a0
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-66-gefb32a0/170-linux/)
+ s3://rtklib-ci-builds/v1.0-66-gefb32a0/170-linux

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-66-gefb32a0
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-66-gefb32a0/170-osx/)
+ s3://rtklib-ci-builds/v1.0-66-gefb32a0/170-osx

**Comment by Paakkit** [comment]
ftp://ftp.cddis.eosdis.nasa.gov/gnss/data/campaign/mgex/daily/rinex3/2018/brdm/
brdm1430.18p.Z

PR:
G19 2018  5 23 12  0  0 -.434169545770E-03  .295585778076E-11  .000000000000E+00
      .710000000000E+02  .384062500000E+02  .398266575274E-08  .143592278904E+01
      .174716114998E-05  .987692561466E-02  .918097794056E-05  .515371651077E+04
      .302400000000E+06 -.894069671631E-07  .270449926445E+01 -.135973095894E-06
      .980418104818E+00  .219625000000E+03  .118420085531E+01 -.796497463031E-08
      .134291314180E-09  .000000000000E+00  .200200000000E+04  **.100000000000E+01**
      .200000000000E+01  .000000000000E+00 -.153668224812E-07  .710000000000E+02
      .295219200000E+06  **.000000000000E+00**
      
vs. 
    
Reference 
G19 2018 05 23 12 00 00-4.341695457697e-04 2.955857780762e-12 0.000000000000e+00
     7.100000000000e+01 3.840625000000e+01 3.982665894021e-09 1.435922789045e+00
     1.747161149979e-06 9.876925614662e-03 9.180977940559e-06 5.153716510773e+03
     3.024000000000e+05-8.940696716309e-08 2.704499264450e+00-1.359730958939e-07
     9.804181048179e-01 2.196250000000e+02 1.184200855313e+00-7.964974630307e-09
     1.342913080577e-10 1.000000000000e+00 2.002000000000e+03 **0.000000000000e+00**
     2.000000000000e+00 0.000000000000e+00-1.536682248116e-08 7.100000000000e+01
     2.952180000000e+05 **4.000000000000e+00**

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-67-g43df606
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-67-g43df606/172-linux/)
+ s3://rtklib-ci-builds/v1.0-67-g43df606/172-linux

**Comment by Paakkit** [comment]
Fixed a Glonass bug.
Here's a similar GLO comparison:

ftp://ftp.cddis.eosdis.nasa.gov/gnss/data/campaign/mgex/daily/rinex3/2018/brdm/
brdm1430.18p.Z

PR:
R15 2018  5 23  9 15  0 -.106161460280E-04  .000000000000E+00  **.342000000000E+05**
      .779473681641E+04 -.431127548218E-01  .000000000000E+00  .000000000000E+00
      .151659750977E+05  .260372066498E+01  .000000000000E+00  .000000000000E+00
      .190128964844E+05 -.205054378510E+01 -.931322574615E-09  **.420000000000E+04**

vs.

Reference
R15 2018 05 23 09 15 00-1.061614602804e-05 0.000000000000e+00 **2.916000000000e+05**
     7.794736816406e+03-4.311275482178e-02 0.000000000000e+00 0.000000000000e+00
     1.516597509766e+04 2.603720664978e+00 0.000000000000e+00 0.000000000000e+00
     1.901289648438e+04-2.050543785095e+00-9.313225746155e-10 **0.000000000000e+00**

**Comment by Paakkit** [comment]
Difference in time handling + age of data.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-69-gf2eec90
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-69-gf2eec90/177-linux/)
+ s3://rtklib-ci-builds/v1.0-69-gf2eec90/177-linux

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-69-gf2eec90
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-69-gf2eec90/177-osx/)
+ s3://rtklib-ci-builds/v1.0-69-gf2eec90/177-osx

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-70-gafdd585
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-70-gafdd585/179-osx/)
+ s3://rtklib-ci-builds/v1.0-70-gafdd585/179-osx

**Comment by Paakkit** [comment]
ftp://ftp.cddis.eosdis.nasa.gov/gnss/data/campaign/mgex/daily/rinex3/2018/brdm/
brdm1490.18p.Z

Here's one example on how they now look:
Piksi rinex - top line
Ref rinex - bottom line

```

G12 2018  5 29 14  0  0  .330743379891E-03 -.238742359215E-11  .000000000000E+00
G12 2018 05 29 14 00 00 3.307433798909e-04-2.387423592154e-12 0.000000000000e+00

  .390000000000E+02   .304375000000E+02   .426124892669E-08   .267330493998E+01
 3.900000000000e+01  3.043750000000e+01  4.261248926693e-09  2.673304939984e+00      
      
  .132061541080E-05   .720955443103E-02   .564381480217E-06   .515358493233E+04
 1.320615410805e-06  7.209554431029e-03  5.643814802170e-07  5.153584932327e+03     
      
  .223200000000E+06  -.968575477600E-07   .149854767291E+01  -.104308128357E-06
 2.232000000000e+05 -9.685754776001e-08  1.498547672914e+00 -1.043081283569e-07      
      
  .986297481878E+00   .378031250000E+03   .986171072589E+00  -.812926718804E-08
 9.862974818776e-01  3.780312500000e+02  9.861710725893e-01 -8.129267188037e-09      
      
 -.271439877989E-10   .000000000000E+00   .200300000000E+04   .100000000000E+01
-2.714398779890e-11  1.000000000000e+00  2.003000000000e+03  0.000000000000e+00     
     
  .200000000000E+01   .000000000000E+00  -.125728547573E-07   .390000000000E+02
 2.000000000000e+00  0.000000000000e+00 -1.257285475731e-08  3.900000000000e+01      
      
 -.121141440000E+10   .000000000000E+00
 2.160000000000e+05  4.000000000000e+00 

```

```

R17 2018  5 29 12 15  0  .136058777571E-03  .272848410532E-11  .450000000000E+05
R17 2018 05 29 12 15 00 1.360587775707e-04 2.728484105319e-12 2.160000000000e+05

 .141553955078E+05  -.270573520660E+01   .372529029846E-08  .000000000000E+00
1.415539550781e+04 -2.705735206604e+00  3.725290298462e-09 0.000000000000e+00      
      
 .540757910156E+04   .768354415894E+00  -.931322574615E-09  .400000000000E+01
5.407579101562e+03  7.683544158936e-01 -9.313225746155e-10 4.000000000000e+00     
      
 .205343486328E+05   .166075229645E+01   .000000000000E+00  .420000000000E+04
2.053434863281e+04  1.660752296448e+00  0.000000000000e+00 0.000000000000e+00   

```

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-71-gec24a36
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-71-gec24a36/184-linux/)
+ s3://rtklib-ci-builds/v1.0-71-gec24a36/184-linux

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-71-gec24a36
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-71-gec24a36/184-osx/)
+ s3://rtklib-ci-builds/v1.0-71-gec24a36/184-osx

**Pull request merged**
