### PR TITLE
Decode B2a and add Skylark configuration file

### PR DESCRIPTION
**Pull request by tao-swift**
This PR enables B2a decoding in RTCM3 so that Skylark BDS corrections can be properly used. Also updated the Skylark L1/L5 configuration file.

### CODE REVIEW

**Review by ljbade — APPROVED** [review]

**Review by dgburr — CHANGES_REQUESTED** [review]
Shouldn't we remove the old configuration file as well (even better: move the old file into the `conf` directory and then apply the changes)?

**Comment by tao-swift** [comment]
> Shouldn't we remove the old configuration file as well (even better: move the old file into the `conf` directory and then apply the changes)?

RTKLIB's folder structure has changed a bit with the latest b34 patch. Before the rebase, we have
`RTKLIB/app/rtkrcv/conf/rtk_skylark_l1l5.conf`

After the rebase, we have
`RTKLIB/app/rtkrcv/rtk_skylark_l1l5.conf`, and 
`RTKLIB/app/consapp/rtkrcv/conf/rtk_skylark_l1l5.conf`. I removed the one in `RTKLIB/app/rtkrcv/`, hopefully that's ok with you.

**Comment by tao-swift** [comment]
Any further thoughts @dgburr ?

**Comment by dgburr** [comment]
@tao-swift: I'm still working on testing your changes.  I got a bit stuck because of https://github.com/swift-nav/RTKLIB/pull/68 but now that I have a solution I am moving again. 

However one thing that I noticed is that you disabled `out-outsingle`.  Would you have an issue switching it back on?

**Comment by tao-swift** [comment]
> @tao-swift: I'm still working on testing your changes. I got a bit stuck because of #68 but now that I have a solution I am moving again.
> 
> However one thing that I noticed is that you disabled `out-outsingle`. Would you have an issue switching it back on?

Didn't deliberately disable it, should be no problem switching it back on.

**Review by dgburr — APPROVED** [review]
LGTM

**Pull request merged**
