### PR TITLE
Add instructions for signing mac binaries.

### PR DESCRIPTION
**Pull request by john-michaelburke**

### CODE REVIEW

**Comment by silverjam** [comment]
This is a public repo and we should try to generalize these instruction for other apps too.  Let's move it here: https://swift-nav.atlassian.net/wiki/spaces/ENG/pages/1469188493/Swift+Console+-+Digital+Signature+Process (maybe make this page more generic too?).

**Comment by john-michaelburke** [comment]
> This is a public repo and we should try to generalize these instruction for other apps too. Let's move it here: https://swift-nav.atlassian.net/wiki/spaces/ENG/pages/1469188493/Swift+Console+-+Digital+Signature+Process (maybe make this page more generic too?).

Yeah it seems like there are two modes for signing, if you are signing a ".app" file it requires slightly different instructions than a ".zip" filled with binaries. I will try to generalize though.

**Comment by john-michaelburke** [comment]
@silverjam Do you want me to completely remove this instructional? I added a generic description of the process here:
https://swift-nav.atlassian.net/wiki/spaces/ENG/pages/1469188493/Swift+Console+-+Digital+Signature+Process#Mac-Code-Signing
The unzip commands and such here help to maintain the structure of the zip file compared to other operating systems. All secrets have been removed here as well. What are your thoughts?

**Comment by silverjam** [comment]
> @silverjam Do you want me to completely remove this instructional? I added a generic description of the process here:
> 
> https://swift-nav.atlassian.net/wiki/spaces/ENG/pages/1469188493/Swift+Console+-+Digital+Signature+Process#Mac-Code-Signing
> 
> The unzip commands and such here help to maintain the structure of the zip file compared to other operating systems. All secrets have been removed here as well. What are your thoughts? 

I think it'd make since to just link to the internal page with something like "For Swift developers see this wiki page on how to digitally sign a release of sbp2rinex and str2str." -- then let's add a section to that wiki page with the zip command that's specific to rtklib.

**Pull request merged**
