### PR TITLE
Rebase converter on 2.4.3b29

### PR DESCRIPTION
**Pull request by mbavaro**
Rebased our converter on top of RTKLIB 2.4.3b29
This seems to generate good messages with SBAS, Beidou and Galileo on both frequencies.

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-81-g0d43d91
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-81-g0d43d91/161-linux/)
+ s3://rtklib-ci-builds/v1.0-81-g0d43d91/161-linux

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-81-g0d43d91-dirty
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-81-g0d43d91-dirty/161-osx/)
+ s3://rtklib-ci-builds/v1.0-81-g0d43d91-dirty/161-osx

**Comment by mbavaro** [comment]
@switanis could you try this version of the converter?

**Comment by mbavaro** [comment]
master does not seem to generate BDS and Galileo obs, merging

**Pull request merged**
