### PR TITLE
Merge upstream release 2.4.3 b33 [INFRA-49]

### PR DESCRIPTION
**Pull request by silverjam**
Merged in https://github.com/tomojitakasu/RTKLIB/tree/rtklib_2.4.3 to our branch, only conflicts where around lines like this:

```c
for (m=0;m<5;m++) { /* m=0:gps/sbs,1:glo,2:gal,3:bds,4:qzs */
```

### CODE REVIEW

**Comment by silverjam** [comment]
@jaredw42 @swiftnav-ram Can one of you test this to see if it works?

**Comment by anonymous-travis-swiftnav** [comment]
## 9a71b5f
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=9a71b5f/335-linux/)
+ s3://rtklib-ci-builds/9a71b5f/335-linux

**Comment by anonymous-travis-swiftnav** [comment]
## 9a71b5f
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=9a71b5f/335-osx/)
+ s3://rtklib-ci-builds/9a71b5f/335-osx

**Comment by anonymous-travis-swiftnav** [comment]
## 64088b1
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=64088b1/339-linux/)
+ s3://rtklib-ci-builds/64088b1/339-linux

**Comment by anonymous-travis-swiftnav** [comment]
## c5b7047
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=c5b7047/341-linux/)
+ s3://rtklib-ci-builds/c5b7047/341-linux

**Comment by anonymous-travis-swiftnav** [comment]
## c5b7047
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=c5b7047/341-osx/)
+ s3://rtklib-ci-builds/c5b7047/341-osx

**Comment by anonymous-travis-swiftnav** [comment]
## f372200
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=f372200/343-linux/)
+ s3://rtklib-ci-builds/f372200/343-linux

**Comment by anonymous-travis-swiftnav** [comment]
## f372200
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=f372200/343-osx/)
+ s3://rtklib-ci-builds/f372200/343-osx

**Comment by anonymous-travis-swiftnav** [comment]
## 8618f10
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=8618f10/345-linux/)
+ s3://rtklib-ci-builds/8618f10/345-linux

**Comment by anonymous-travis-swiftnav** [comment]
## 8d3e4e0
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=8d3e4e0/349-linux/)
+ s3://rtklib-ci-builds/8d3e4e0/349-linux

**Comment by anonymous-travis-swiftnav** [comment]
## 8d3e4e0
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=8d3e4e0/349-osx/)
+ s3://rtklib-ci-builds/8d3e4e0/349-osx

**Comment by silverjam** [comment]
Builds:
+ Windows:
    - [str2str.zip](https://github.com/swift-nav/RTKLIB/files/4048626/str2str.zip)
    - [sbp2rinex.zip](https://github.com/swift-nav/RTKLIB/files/4048628/sbp2rinex.zip)
+ Linux:
   - [str2str.zip](https://github.com/swift-nav/RTKLIB/files/4048631/str2str.zip)
   - [sbp2rinex.zip](https://github.com/swift-nav/RTKLIB/files/4048630/sbp2rinex.zip)
+ macOS:
   - [str2str.zip](https://github.com/swift-nav/RTKLIB/files/4048634/str2str.zip)
   - [sbp2rinex.zip](https://github.com/swift-nav/RTKLIB/files/4048635/sbp2rinex.zip)

**Pull request merged**
