### PR TITLE
expose udp client functionality

### PR DESCRIPTION
**Pull request by silverjam**

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## 2020.04.08-2-gff109d1
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=2020.04.08-2-gff109d1/377-osx/)
+ s3://rtklib-ci-builds/2020.04.08-2-gff109d1/377-osx

**Comment by anonymous-travis-swiftnav** [comment]
## 2020.04.08-2-gff109d1
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=2020.04.08-2-gff109d1/377-linux/)
+ s3://rtklib-ci-builds/2020.04.08-2-gff109d1/377-linux

**Comment by anonymous-travis-swiftnav** [comment]
## 2020.04.08-2-gff109d1
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=2020.04.08-2-gff109d1/377-windows/)
+ s3://rtklib-ci-builds/2020.04.08-2-gff109d1/377-windows

**Comment by switanis** [comment]
Tested on Linux and it's working.

**Comment by anonymous-travis-swiftnav** [comment]
## 2020.04.08-3-gb02080b
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=2020.04.08-3-gb02080b/382-linux/)
+ s3://rtklib-ci-builds/2020.04.08-3-gb02080b/382-linux

**Comment by anonymous-travis-swiftnav** [comment]
## 2020.04.08-3-gb02080b
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=2020.04.08-3-gb02080b/382-osx/)
+ s3://rtklib-ci-builds/2020.04.08-3-gb02080b/382-osx

**Comment by anonymous-travis-swiftnav** [comment]
## 2020.04.08-3-gb02080b
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=2020.04.08-3-gb02080b/382-windows/)
+ s3://rtklib-ci-builds/2020.04.08-3-gb02080b/382-windows

**Pull request merged**
