### PR TITLE
Fix handling of ant1-postype/ant2-postype options

### PR DESCRIPTION
**Pull request by dgburr**
Fix a bug introduced in changeset 1c45a3c51365d2b1acd203af0ce87138211a73da with the handling of `ant1-postype`/`ant2-postype` options

### CODE REVIEW

**Comment by tao-swift** [comment]
hmm, shall we merge https://github.com/swift-nav/RTKLIB/pull/61 first and then move onto the current PR?

**Comment by dgburr** [comment]
The idea was to merge these changes into your branch (if you approve) and then merge #61

**Comment by tao-swift** [comment]
> The idea was to merge these changes into your branch (if you approve) and then merge #61

I can add the hints in my PR. For the bug commit, we leave it for a separate PR (e.g., the current one) so that we don't mix things up, does that sound good?

**Comment by dgburr** [comment]
> > The idea was to merge these changes into your branch (if you approve) and then merge #61
> 
> I can add the hints in my PR. For the bug commit, we leave it for a separate PR (e.g., the current one) so that we don't mix things up, does that sound good?

No objections, it just means at the end that we will end up with 2 commits to master instead of 1.

**Comment by tao-swift** [comment]
> > > The idea was to merge these changes into your branch (if you approve) and then merge #61
> > 
> > 
> > I can add the hints in my PR. For the bug commit, we leave it for a separate PR (e.g., the current one) so that we don't mix things up, does that sound good?
> 
> No objections, it just means at the end that we will end up with 2 commits to master instead of 1.

Added changes with related to your comments, mind giving a quick review?

**Comment by tao-swift** [comment]
The bug fix commit looks good to me. I hesitated a bit on that during the review, but forgot it when looking at the `refpos` option.

**Review by tao-swift — APPROVED** [review]

**Pull request merged**
