### PR TITLE
Flags adjustments

### PR DESCRIPTION
**Pull request by mbavaro**
Plus preliminary SBAS and Beidou support

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-65-g26b8cbd
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-65-g26b8cbd/151-linux/)
+ s3://rtklib-ci-builds/v1.0-65-g26b8cbd/151-linux

**Comment by pgrgich** [comment]
Lgtm. Might be better to split the changes into different commits in future - e.g. rename, BDS support and flag handling change.

**Comment by mbavaro** [comment]
Agreed, I had planned to do that in steps but since there was a need today I put it out quickly :)

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-65-g26b8cbd
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-65-g26b8cbd/151-osx/)
+ s3://rtklib-ci-builds/v1.0-65-g26b8cbd/151-osx

**Pull request merged**
