### PR TITLE
Add support for posting build artifact URLs to PRs

### PR DESCRIPTION
**Pull request by silverjam**
Adapted scripts from piksi_buildroot to a comment to PRs when a build artifact is ready, and upload build artifacts from PRs to S3 (which is not possible with travis by default).

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-65-gce1e452
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=rtklib-ci-builds/138osx/app/convbin/gcc/sbp2rinex/)
+ s3://rtklib-ci-builds/rtklib-ci-builds/138osx/app/convbin/gcc/sbp2rinex

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-65-gce1e452
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=rtklib-ci-builds/140linux/app/convbin/gcc/sbp2rinex/)
+ s3://rtklib-ci-builds/rtklib-ci-builds/140linux/app/convbin/gcc/sbp2rinex

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-65-gce1e452
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=rtklib-ci-builds/140osx/app/convbin/gcc/sbp2rinex/)
+ s3://rtklib-ci-builds/rtklib-ci-builds/140osx/app/convbin/gcc/sbp2rinex

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-65-g0ab2d59
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-65-g0ab2d59/143-linux/sbp2rinex/)
+ s3://rtklib-ci-builds/v1.0-65-g0ab2d59/143-linux/sbp2rinex

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-65-g0ab2d59
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-65-g0ab2d59/143-osx/sbp2rinex/)
+ s3://rtklib-ci-builds/v1.0-65-g0ab2d59/143-osx/sbp2rinex

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-65-gee695c4
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-65-gee695c4/146-linux/sbp2rinex/)
+ s3://rtklib-ci-builds/v1.0-65-gee695c4/146-linux/sbp2rinex

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-65-g0d86f81
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-65-g0d86f81/148-linux/)
+ s3://rtklib-ci-builds/v1.0-65-g0d86f81/148-linux

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-65-g0d86f81
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-65-g0d86f81/148-osx/)
+ s3://rtklib-ci-builds/v1.0-65-g0d86f81/148-osx

**Comment by silverjam** [comment]
@mbavaro @denniszollo this should be ready now

**Pull request merged**
