### PR TITLE
Add RTCM1042 for debugging

### PR DESCRIPTION
**Pull request by mbavaro**
@scarcanague 

oh, the linting tool made a mess, but the 1042 function is the only thing I added.
Seems to work against our SBF converter 
```
C11 2018  9 20 17  0  0 -.689075444825E-03 -.175539582870E-10  .000000000000E+00
C11 2018 09 20 17 00 00-6.890754448250E-04-1.755395828695E-11 0.000000000000E+00

      .100000000000E+01  .348125000000E+02  .359372112148E-08  .307909843903E+01
     1.000000000000E+00 3.481250000000E+01 3.593721121481E-09 3.079098439026E+00

      .164145603776E-05  .227916706353E-02  .319769605994E-05  .528260324287E+04
     1.641456037760E-06 2.279167063534E-03 3.197696059942E-06 5.282603242874E+03

      .406800000000E+06  .274740159512E-07  .765506335234E+00 -.400468707085E-07
     4.068000000000E+05 2.747401595116E-08 7.655063352344E-01-4.004687070847E-08
  
      .986180445505E+00  .313890625000E+03 -.236633285627E+01 -.684564229134E-08
     9.861804455054E-01 3.138906250000E+02-2.366332856267E+00-6.845642291336E-09
    
      .271797035723E-09  .000000000000E+00  .663000000000E+03  .000000000000E+00
     2.717970357232E-10 0.000000000000E+00 6.630000000000E+02

      .200000000000E+01  .000000000000E+00  .390000000000E-08  .160000000000E-08
      2.000000000000E+00 0.000000000000E+00 3.900000000000E-09 1.600000000000E-09

     .416790988871E+06  .000000000000E+00
     4.068180000000E+05 0.000000000000E+00
     
     
C12 2018  9 20 17  0  0  .619098544121E-03  .201341165962E-10  .379470760370E-18
C12 2018 09 20 17 00 00 6.190985441208E-04 2.013411659618E-11 3.794707603699E-19

      .100000000000E+01  .382187500000E+02  .354336188096E-08 -.229072542440E+01
     9.000000000000E+00 3.821875000000E+01 3.543361880959E-09-2.290725424400E+00

     .168569386005E-05  .253677391447E-02  .310689210892E-05  .528261083984E+04
     1.685693860054E-06 2.536773914471E-03 3.106892108917E-06 5.282610839844E+03

     .406800000000E+06  .670552253723E-07  .755151509949E+00  .232830643654E-08
     4.068000000000E+05 6.705522537231E-08 7.551515099486E-01 2.328306436539E-09

     .985032675090E+00  .308500000000E+03 -.245768668337E+01 -.687100049046E-08
     9.850326750905E-01 3.085000000000E+02-2.457686683372E+00-6.871000490464E-09

     .314655963827E-09  .000000000000E+00  .663000000000E+03  .000000000000E+00
     3.146559638267E-10 0.000000000000E+00 6.630000000000E+02

     .200000000000E+01  .000000000000E+00  .260000000000E-08  .000000000000E+00
     2.000000000000E+00 0.000000000000E+00 2.600000000000E-09-3.000000000000E-10

     .416790988871E+06  .000000000000E+00
     4.068180000000E+05 8.000000000000E+00
```

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2-7-g1ef604c
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.2-7-g1ef604c/303-linux/)
+ s3://rtklib-ci-builds/v1.2-7-g1ef604c/303-linux

**Comment by scarcanague** [comment]
@mbavaro It seems it is Beidou decoding is present in the official repo: https://github.com/tomojitakasu/RTKLIB/blob/master/src/rtcm3.c#L1152

Is our repo just out of sync??

**Comment by anonymous-travis-swiftnav** [comment]
## v1.2-7-g1ef604c
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.2-7-g1ef604c/303-osx/)
+ s3://rtklib-ci-builds/v1.2-7-g1ef604c/303-osx

**Comment by mbavaro** [comment]
damn, our repo is aligned to 2.4.3b29 🙄

**Comment by mbavaro** [comment]
let's use tomoji's master to compare then..

**Comment by mbavaro** [comment]
I'll try rebasing vs b31 instead..

**Pull request closed without merging**
