### PR TITLE
Windows GA.

### PR DESCRIPTION
**Pull request by john-michaelburke**
* Adds windows as a build and release target.
* Fixed an issue where Windows would complain about SIG_HUP and SIG_PIPE not being valid signals for windows, since we ignore them just defining them seems to resolve the issue.
* Deleted the Jenkinsfile.
* Renamed the zip filenames to be consistent with each other (@dgburr is this acceptable with you?)
* @dgburr I see we were additionally building for mingw and vs14 on appveyor, is this still needed or can we delete it as well?

Here is a test tag:
https://github.com/swift-nav/RTKLIB/releases/tag/v2.3.windows

### CODE REVIEW

**Review by silverjam — APPROVED** [review]
MinGW should be enough, as long as the built binary doesn't need any runtime DLLs

**Comment by silverjam** [comment]
> * @dgburr I see we were additionally building for mingw and vs14 on appveyor, is this still needed or can we delete it as well?

I vote for deleting appveyor, shouldn't be necessary anymore

**Review by dgburr — APPROVED** [review]
I'm fine with renaming the .zip files to be consistent.  

I have no idea why there was previously a version being built with mingw as well as Visual Studio.  My guess would be (as hinted by @silverjam) that the mingw build was not truly static and had some kind of dependency on a DLL.

@switanis do you have any idea why there were previously multiple versions being built for WIndows?

**Comment by dgburr** [comment]
In fact it looks like @switanis was the one who added support for building with VS: https://github.com/swift-nav/RTKLIB/pull/12

**Pull request merged**
