### PR TITLE
Add support for BDS and GAL ephemeris

### PR DESCRIPTION
**Pull request by Paakkit**
Step 1. in the introduction of new SBP ephemeris messages.

### CODE REVIEW

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-66-ga2f92f7
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-66-ga2f92f7/169-linux/)
+ s3://rtklib-ci-builds/v1.0-66-ga2f92f7/169-linux

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-66-ga2f92f7
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-66-ga2f92f7/169-osx/)
+ s3://rtklib-ci-builds/v1.0-66-ga2f92f7/169-osx

**Comment by mbavaro** [comment]
what about comparing the BDS/GAL Rinex nav output with a BRDM from MGEX? ftp://ftp.cddis.eosdis.nasa.gov/gnss/data/campaign/mgex/daily/rinex3/2018/brdm

**Comment by Paakkit** [comment]
I'll compare against those Rinex files after they upload the records for today.

In the meanwhile, sbp2rinex vs. piksi decoder:

**sbp2rinex**
C12 2018  5 23  9  0  0  .452251173556E-03  .122151178061E-10  .000000000000E+00
      .162000000000E+03  .479218750000E+02  .322442006429E-08 -.303179722998E+01
      .237068161368E-05  .230340112466E-02  .760657712817E-05  .528260980034E+04
      **.291614000000E+06**  .155065208673E-06  .287281343738E+01 -.279396772385E-08
      .984313658169E+00  .216781250000E+03 -.238306038824E+01 -.669599320071E-08
      .515378628663E-09  .120000000000E+02  .200200000000E+04  .100000000000E+01
      .200000000000E+01  .000000000000E+00  .259999999308E-08 -.299999997067E-09
     **-.819817031400E+09**  .100000000000E+01

**Piksi decoder:**
C12 2018  5 23  9  0  0  4.52251173556E-04  1.22151178061E-11  0.00000000000E+00  
      1.62000000000E+02  4.79218750000E+01  3.22442002432E-09 -3.03179722998E+00  
      2.37068161368E-06  2.30340112466E-03  7.60657712817E-06  5.28260980034E+03  
      **2.91600000000E+05**  1.55065208673E-07  2.87281343738E+00 -2.79396772385E-09  
      9.84313658169E-01  2.16781250000E+02 -2.38306038824E+00 -6.69599320071E-09  
      5.15378610445E-10  0.00000000000E+00  6.46000000000E+02  0.00000000000E+00  
      2.00000000000E+00  0.00000000000E+00  2.60000000000E-09 -3.00000000000E-10  
      **2.91776000000E+05**  1.00000000000E+00 

Piksi decoder prints the **2.91600000000E+05** before the 14 seconds offset is added.
Somehow **-.819817031400E+09** comes as negative on sbp2rinex conversion...!

**Comment by Paakkit** [comment]
And week number obviously also shows the week number offset:
 .200200000000E+04 vs. 6.46000000000E+02

**Comment by Paakkit** [comment]
https://github.com/swift-nav/RTKLIB/blob/master/src/rinex.c#L2352-L2358
It expects BDS time, but we have time in GPS time.

**Comment by Paakkit** [comment]
ftp://ftp.cddis.eosdis.nasa.gov/gnss/data/campaign/mgex/daily/rinex3/2018/brdm/
brdm1430.18p.Z

PR:
C12 2018  5 23  9  0  0  .452251173556E-03  .122151178061E-10  .000000000000E+00
      **.162000000000E+03**  .479218750000E+02  .322442006429E-08 -.303179722998E+01
      .237068161368E-05  .230340112466E-02  .760657712817E-05  .528260980034E+04
      **.291614000000E+06**  .155065208673E-06  .287281343738E+01 -.279396772385E-08
      .984313658169E+00  .216781250000E+03 -.238306038824E+01 -.669599320071E-08
      .515378628663E-09  **.120000000000E+02**  **.200200000000E+04**  **.100000000000E+01**
      .200000000000E+01  .000000000000E+00  .259999999308E-08 -.299999997067E-09
     **-.819817031400E+09**  **.100000000000E+01**

vs.

Reference
C12 2018 05 23 09 00 00 4.522511735559e-04 1.221511780614e-11 0.000000000000e+00
     **1.000000000000e+00** 4.792187500000e+01 3.224420024322e-09-3.031797229975e+00
     2.370681613684e-06 2.303401124664e-03 7.606577128172e-06 5.282609800339e+03
     **2.916000000000e+05** 1.550652086735e-07 2.872813437377e+00-2.793967723846e-09
     9.843136581691e-01 2.167812500000e+02-2.383060388236e+00-6.695993200708e-09
     5.153786104449e-10 **0.000000000000e+00** **6.460000000000e+02** **0.000000000000e+00**
     2.000000000000e+00 0.000000000000e+00 2.600000000000e-09-3.000000000000e-10
     **2.916000000000e+05** **0.000000000000e+00**

**Comment by Paakkit** [comment]
AODE fields have mismatches since we don't use collect the parameters.

14 seconds time difference between gps time and bds time is visible.
Shall I fix this to have alignment?

Beidou week difference is visible.
Shall I fix this to have alignment?

`eph.ttr` has bigger issue. I was not able to figure out how to get that one correct.

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-67-gaa30855
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-67-gaa30855/174-linux/)
+ s3://rtklib-ci-builds/v1.0-67-gaa30855/174-linux

**Comment by anonymous-travis-swiftnav** [comment]
## v1.0-67-gaa30855
+ [Artifacts (S3 / AWS Console)](https://console.aws.amazon.com/s3/home?region=us-west-2&bucket=rtklib-ci-builds&prefix=v1.0-67-gaa30855/174-osx/)
+ s3://rtklib-ci-builds/v1.0-67-gaa30855/174-osx

**Comment by Paakkit** [comment]
Pushed a commit to align BDS time scale.
Here's the comparison:

ftp://ftp.cddis.eosdis.nasa.gov/gnss/data/campaign/mgex/daily/rinex3/2018/brdm/
brdm1430.18p.Z

PR:
C12 2018  5 23  9  0  0  .452251173556E-03  .122151178061E-10  .000000000000E+00
      .162000000000E+03  .479218750000E+02  .322442006429E-08 -.303179722998E+01
      .237068161368E-05  .230340112466E-02  .760657712817E-05  .528260980034E+04
      **.291600000000E+06**  .155065208673E-06  .287281343738E+01 -.279396772385E-08
      .984313658169E+00  .216781250000E+03 -.238306038824E+01 -.669599320071E-08
      .515378628663E-09  .120000000000E+02  **.646000000000E+03**  .100000000000E+01
      .200000000000E+01  .000000000000E+00  .259999999308E-08 -.299999997067E-09
      .291768600000E+06  .100000000000E+01

vs.

Reference
C12 2018 05 23 09 00 00 4.522511735559e-04 1.221511780614e-11 0.000000000000e+00
     1.000000000000e+00 4.792187500000e+01 3.224420024322e-09-3.031797229975e+00
     2.370681613684e-06 2.303401124664e-03 7.606577128172e-06 5.282609800339e+03
     **2.916000000000e+05** 1.550652086735e-07 2.872813437377e+00-2.793967723846e-09
     9.843136581691e-01 2.167812500000e+02-2.383060388236e+00-6.695993200708e-09
     5.153786104449e-10 0.000000000000e+00 **6.460000000000e+02** 0.000000000000e+00
     2.000000000000e+00 0.000000000000e+00 2.600000000000e-09-3.000000000000e-10
     2.916000000000e+05 0.000000000000e+00

**Comment by mbavaro** [comment]
rearranged:

```

C12 2018  5 23  9  0  0 .452251173556E-03 .122151178061E-10 .000000000000E+00
C12 2018 05 23 09 00 00 4.52251173555e-04 1.22151178061e-11 0.00000000000e+00

.162000000000E+03 .479218750000E+02 .322442006429E-08 -.303179722998E+01
1.00000000000e+00 4.79218750000e+01 3.22442002432e-09 -3.03179722998e+00

.237068161368E-05 .230340112466E-02 .760657712817E-05  .528260980034E+04
2.37068161368e-06 2.30340112466e-03 7.60657712817e-06  5.28260980034e+03

.291600000000E+06 .155065208673E-06 .287281343738E+01 -.279396772385E-08
2.91600000000e+05 1.55065208673e-07 2.87281343738e+00 -2.79396772385e-09

.984313658169E+00 .216781250000E+03 -.23830603882E+01 -.669599320071E-08
9.84313658169e-01 2.16781250000e+02 -2.3830603882e+00 -6.69599320071e-09

**.515378628663E-09** .120000000000E+02 .646000000000E+03 .1000000000000E+01
**5.15378610445e-10** 0.00000000000e+00 6.46000000000e+02 0.000000000000e+00

.200000000000E+01 .000000000000E+00 **.259999999308E-08** **-.299999997067E-09**
2.00000000000e+00 0.00000000000e+00 **2.60000000000e-09** **-3.00000000000e-10**

.291768600000E+06 .100000000000E+01
2.91600000000e+05 0.00000000000e+00
```

the two `tgd`s and `idot` are slightly different, as they would suffer from some rounding error.. they are float and are converted to doubles but the same happens elsewhere and does not appear to be a problem. I'll try today to see if this can be fixed in `swiftnav.c`

**Comment by mbavaro** [comment]
Mmm `tgd`s should be OK, but our `inc_dot` has `pi` in it... (radians vs semi-circles) so although it's only 14 bits, we corrupt the remaining 10 bits by putting `pi` in it.
Funny, because per domment here https://github.com/swift-nav/libswiftnav-private/blob/master/refactor/common/libswiftnav/ephemeris.h#L117 it should indeed be semi-circles.

**Pull request merged**
