### PR TITLE
Fix read/write position of LLI field in RINEX files

### PR DESCRIPTION
**Pull request by dgburr**
According to http://acc.igs.org/misc/rinex304.pdf there should be a space in between the phase range and LLI fields.  Also see the example on page 70 (A16)

### CODE REVIEW

**Comment by tao-swift** [comment]
it doesn't seem to that we need to include a space. There are F14.3 for observation, I1 for LLI, and I1 for SSI. The LLI or SSI field can be blank. 
Screen Shot 2022-03-29 at 10 18 05 am
5a.png)

**Comment by dgburr** [comment]
Look at the example on page A16
Screenshot at 2022-03-29 01-23-57

**Comment by tao-swift** [comment]
> Look at the example on page A16 Screenshot at 2022-03-29 01-23-57

Yeah, for example, for the first satellite, the phase observation is 16119.980 with 3 digits, and then a black space (i used a *) for the LLI, and then 7 indicating the signal strength.
`G06 21110991.756 16119.980*7 12560.510 4 21110991.441 25.543`

**Comment by dgburr** [comment]
The header in the example is `C1C L1W L2W C1W S2W` meaning that there is no signal strength column at the indicated position

**Comment by tao-swift** [comment]
> The header in the example is `C1C L1W L2W C1W S2W` meaning that there is no signal strength column at the indicated position: this `7` represents LLI for L1, not signal strength (the `4` is also an LLI value for L2)

`C1C L1W L2W C1W S2W` these are indicating that there are 5 observations following the order of these observation types, and each observation consists of m fields with `(m(F14.3, I1, I1))`. The LLI value range is 0-2 (as shown by the &3 operation), and the SSI range is 0-9. Both can be represented with empty field.

**Pull request closed without merging**
